---
title: "Antarctic Whale Project: Single Species"
author: "Ben Weinstein"
date: "`r Sys.time()`"
output: 
  html_document:
    keep_md: true
    number_sections: true
    toc: true
    theme: spacelab
---

```{r,warning=FALSE,message=FALSE,echo=FALSE}
library(knitr)
opts_chunk$set(echo=F,warning=F,message=F,fig.width = 11,fig.height = 7)
library(raster)
library(reshape2)
library(ggplot2)
library(ggbiplot)
library(ggmap)
library(dplyr)
library(chron)
library(stringr)
library(maps)
```

```{r}
#read whale data
mdat<-read.csv("InputData/Antarctic Humpback overlap with krill fisheries -3085052751565071394.csv")

#name env columns
#Create a oceandepth in km 
mdat$ocean<-round(mdat$ETOPO1.Elevation * -1 /1000,3)
mdat$coast<-round(mdat$NASA.Distance.to.Coast,1)
mdat$DSST<-mdat$ECMWF.Interim.Full.Daily.SFC.Sea.Ice.Cover
mdat$SST<-mdat$MODIS.Ocean.Terra.OceanColor.4km.Yearly.Daytime.SST
mdat$ChloroA_Aqua<-mdat$MODIS.Ocean.Aqua.OceanColor.4km.Monthly.Chlorophyll.A
mdat$ChloroA_Terra<-mdat$MODIS.Ocean.Terra.OceanColor.4km.Monthly.Chlorophyll.A

#Create an animal tag.
mxy <- as(mdat, "data.frame")
mxy$Animal<-mxy$individual.local.identifier
mxy$x<-mxy$location.long
mxy$y<-mxy$location.lat

#grab set of animals
#mxy<-mxy[mxy$Animal %in% c("112699","121207","131151","112703","121211","131132","112737","131156","12326","123232","112705","154187","121210","131134","131141","112701","131159","131142","131144","154186","123224"),]

#mxy<-mxy[mxy$Animal %in% c("131134","131141"),]
mxy$Animal<-as.numeric(as.factor(mxy$Animal))

#empty coordinates
mxy<-mxy[!is.na(mxy$x),]

#crop by extent
d<-SpatialPointsDataFrame(cbind(mxy$x,mxy$y),data=mxy)
d<-crop(d,y=extent(c(-75,-50,-70,-55)))
mxy<-as.data.frame(d)

#set datestamp
mxy$timestamp<-as.POSIXct(mxy$timestamp,format="%Y-%m-%d %H:%M:%S.000")

#month and year columns
mxy$Month<-months(mxy$timestamp)
mxy$Year<-years(mxy$timestamp)

#remove empty timestamps
mxy<-mxy[!is.na(mxy$timestamp),]

#remove duplicates
mxy<-mxy[!duplicated(data.frame(mxy$timestamp,mxy$Animal)),]
mxy$Month<-factor(mxy$Month,levels=month.name)

#no distance to coast,elevation
mxy<-mxy[!mxy$ETOPO1.Elevation>0,]

#get map
m <- get_map(location=pp,source="google",zoom=5,scale=2,maptype="satellite",color = "bw")
```

# Bathymetry
```{r}
ice<-raster("InputData/ETOPO1_Ice_g_geotiff.tif")
ice<-round(ice*-1/1000,3)
rice<-aggregate(ice,fact=0.1/res(ice))
plot(rice)
ggmap(m)+geom_path(data=mxy, aes(x=x, y=y,col=ocean,group=Animal),size=.5)  + scale_color_continuous(low='blue',high='red') + facet_wrap(~Month)
```

# Distance to coast

```{r}
#coast
distc<-raster("InputData/DistancetoCoast.tif")
rice[rice<0]<-NA
distc[is.na(rice)]<-NA

ggmap(m)+geom_path(data=mxy, aes(x=x, y=y,col=coast,group=Animal),size=.5)  + scale_color_continuous(low='blue',high='red') + facet_wrap(~Month)
```

# Daily Sea surface temperature
```{r}
ggmap(m)+geom_path(data=mxy, aes(x=x, y=y,col=ECMWF.Interim.Full.Daily.SFC.Sea.Surface.Temperature,group=Animal),size=.5)  + scale_color_continuous(low='blue',high='red') + facet_wrap(~Month)
```

# Monthly Sea surface temperature
```{r}

ggmap(m)+geom_path(data=mxy, aes(x=x, y=y,col=SST,group=Animal),size=.5)  + scale_color_continuous(low='blue',high='red') + facet_wrap(~Month)
```

# Chlorophyll A

##Aqua 
```{r}
chl<-list.files("InputData/",pattern="CHL",full.names=T)
chlr<-stack(chl)
names(chl)
sn<-str_match(chl,"chlor_a-(\\d{4})(\\d{2})")[,2:3]
names(chlr)<-paste(sn[,1],sn[,2],sep="_")

plot(log(chlr),addfun=function(){map(add=T)})
ggmap(m)+geom_path(data=mxy, aes(x=x, y=y,col=C),size=.5)  + scale_color_continuous(low='blue',high='red')

ggmap(m)+geom_path(data=mxy, aes(x=x, y=y,col=log(ChloroA_Aqua),group=Animal),size=.5)  + scale_color_continuous(low='blue',high='red') + facet_wrap(~Month)
```

# NPP
```{r}
ggmap(m)+geom_path(data=mxy, aes(x=x, y=y,col=NPP,group=Animal),size=.5)  + scale_color_continuous(low='blue',high='red') + facet_wrap(~Month)
```

###Correlation matrix
```{r}
sxy<-mxy[,colnames(mxy) %in% c("ocean","coast","DSST","SST","ChloroA_Aqua","ChloroA_Terra")]
sxy<-sxy[complete.cases(sxy),]

pca<-prcomp(sxy,scale. = T,center = T)
ggbiplot(pca)
```

```{r,fig.height=12,fig.width=12}
ggpairs(sxy)
```


